; Can specify custom boards dir here.
; [platformio]
; boards_dir = ../RP2040POE

[env:rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower

board = VAAMrp2350_FOCSPE

board_build.variants_dir = ../RP2040POE
board_build.variant = vaam_rp2350spefoc

lib_deps =
	https://github.com/RadicalTray/Arduino_10BASE_T1S

; See build_flags.py for more info
extra_scripts = pre:build_flags.py
